apiVersion: networking.softonic.io/v1alpha1
kind: RateLimit
metadata:
  name: ratelimit-sample-2
  namespace: ratelimitoperatortest
  finalizers:
  - ratelimit.networking.softonic.io
spec:
  targetRef:
    apiVersion: "networking.istio.io/v1alpha3"
    kind:       VirtualService
    name:       vs-test
    namespace:  ratelimitoperatortest
  destinationCluster: "outbound|80||chicken-head-nginx.chicken-head.svc.cluster.local"
  rate:
  - unit: seconds
    requestPerUnit: 100
    dimensions:
    - request_header:
        descriptor_key: remote_address
        header_name: x-custom-ip
  - unit: minute  
    requestPerUnit: 2000
    dimensions:
    - request_header:
        descriptor_key: remote_address
        header_name: x-custom-ip
